added S6 Overlay v1.22.0.0, reworked container init as S6 init script, mounting as S6 service, unmounting as S6 finish script

diff --git a/smb-mount/Dockerfile b/smb-mount/Dockerfile
--- a/smb-mount/Dockerfile
+++ b/smb-mount/Dockerfile
@@ -1,5 +1,7 @@
-FROM alpine
-#MAINTAINER Mumie
+FROM alpine:latest
+
+ARG OVERLAY_VERSION="v1.22.0.0"
+ARG OVERLAY_ARCH="amd64"
 
 ENV SERVERPATH="//192.168.1.1/example" \
     MOUNTPOINT="/mnt/smb" \
@@ -7,17 +9,26 @@ ENV SERVERPATH="//192.168.1.1/example" \
     UMOUNTOPTIONS="-a -t cifs -l" \
     AccessFolder="/mnt"
 
-## Alpine with cifs-utils
-RUN apk add --no-cache --update cifs-utils \
-    && mkdir $MOUNTPOINT \
+RUN apk add --no-cache --update cifs-utils bash tar curl ca-certificates gnupg grep \
+    && curl -o /tmp/s6-overlay.tar.gz -L \
+    "https://github.com/just-containers/s6-overlay/releases/download/${OVERLAY_VERSION}/s6-overlay-${OVERLAY_ARCH}.tar.gz" \
+    && curl -o /tmp/s6-overlay.tar.gz.sig -L \
+    "https://github.com/just-containers/s6-overlay/releases/download/${OVERLAY_VERSION}/s6-overlay-${OVERLAY_ARCH}.tar.gz.sig" \
+    && curl https://keybase.io/justcontainers/key.asc | gpg --import \
+    && gpg --verify /tmp/s6-overlay.tar.gz.sig /tmp/s6-overlay.tar.gz \
+    && tar xfz /tmp/s6-overlay.tar.gz -C / \
+    && apk del tar curl gnupg \
     && rm -rf /tmp/* /var/cache/apk/* /var/lib/apk/lists/*
 
-ADD start.sh /start.sh
-RUN chmod +x /start.sh
+# add local files
+COPY rootfs/ /
+
+#RUN chmod +x /start.sh
 
 #VOLUME ["/mnt"]
 
-CMD ["/start.sh"]
+ENTRYPOINT ["/init"]
 
+# HEALTHCHECK --interval=5s --timeout=2s --retries=20 CMD /healthcheck.sh || exit 1
 # Use this args in docker run
 # --cap-add SYS_ADMIN --cap-add DAC_READ_SEARCH --security-opt apparmor:unconfine
